CREATE TABLE currencyPrices (
    currencyPricesId INT AUTO_INCREMENT PRIMARY KEY,
    date DATETIME DEFAULT NULL,
    usdOfficial DOUBLE DEFAULT NULL,
    usdMEP DOUBLE DEFAULT NULL,
    usdBlue DOUBLE DEFAULT NULL,
    usdCCL DOUBLE DEFAULT NULL
);

