server:
  port: 9090

jwt:
  secret: ${JWT_SECRET}

spring:
  datasource:
    url: ${MYSQL_URI}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
