server:
  port: 9090
  servlet:
    session:
      cookie:
        domain: localhost

jwt:
  secret: "8B887EAA238F79D1E117EA8BBBCED515396CD2ABB9172D476F24F1D432"

spring:
  datasource:
    url: jdbc:mysql://localhost:4000/smartpeso
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

app-properties:
  pepper: "6B888FCB558F79D1E117EA8B1B2AD515396CD2ABB9172D476F66F3C490"